# Generated by Django 2.2.5 on 2019-09-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('customer_since', models.DateTimeField(auto_now=True)),
                ('cell_phone', models.CharField(default='', max_length=15)),
                ('home_phone', models.CharField(default='', max_length=15)),
                ('e_mail', models.CharField(default='', max_length=25)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(default='', max_length=10)),
                ('payment_acct_number', models.CharField(default='', max_length=20)),
                ('payment_acct_security_code', models.IntegerField(default='')),
                ('order_total', models.FloatField(default='', max_length=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ORM.Customer')),
            ],
            options={
                'ordering': ('customer',),
            },
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Order')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=25)),
                ('state', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=11)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Customer')),
            ],
            options={
                'ordering': ('street',),
            },
        ),
    ]
