# Generated by Django 2.2.5 on 2019-09-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('Customer',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
    ]
